
language: go

go:
- "1.10.x"
#- master # master takes quite some time, not needed under normal situations

install:
# Travis CI builds require "appengine" to function correctly
- go get google.golang.org/appengine
- go get github.com/jordan-wright/email
- go get golang.org/x/text/encoding/htmlindex

#deploy:
#  provider: gae
#  keyfile: client-secret.json.enc
#  project: pmd-boomcase
#before_install:
#- openssl aes-256-cbc -K $encrypted_202eef1b0921_key -iv $encrypted_202eef1b0921_iv
#  -in client-secret.json.enc -out client-secret.json -d
