

application: pmd-boomcase
runtime: go
api_version: go1

# ---------- ---------- ---------- ---------- ----------

version: 2016-12-xx-a
# Note: Incompatible with past versions of datastore (new structs)
# Changelog: Major Changes
# Break out cases and drivers frequency response into frequencylow/frequencyhigh

# TODO: Drivers utilizing 10x pixels per inch of diameter (12" = 120px)
# TODO: Driver Multiplier on cases: Adjusts size of drivers on cases

# Changelog: Minor Changes
# Add to Cart changed to "Purchase Now"
# When clicking to edit case, add driver, or edit driver, the others hide properly.
# Clicking a driver to add also enables it for editing populating data to alter dynamically

# TODO: New Extra Options for cases (bigger battery, bottle opener, USB, AC power)
# TODO: Battery life does not display if blank (used to display zero)
# TODO: Speaker grills option which calculates $15 per woofer added to case
# TODO: When a case does not exist, forwards to case selection: /case/5418393301680128 -> /case
# TODO: Sold Out appears when case is marked as sold (also hides Purchase Now button)
# TODO: When adding drivers, take low/high frequencies and add to case being built
# TODO: When saving a custom case, drivers are no longer interactable.
# Changelog: Bugs

# TODO: Diameter for drivers upon creation storing as incorrect values (negative numbers)

# ---------- ---------- ---------- ---------- ----------

handlers:
- url: /resources/stylesheets
  static_dir: resources/stylesheets
  
- url: /resources/javascript
  static_dir: resources/javascript
  
- url: /resources/external
  static_dir: resources/external
  
  
# All URLs ending in .gif .png .jpg are treated as paths to
# static files in the resources/images/ directory. The URL pattern is a
# regular expression, with a grouping that is inserted into the path to the file.
- url: /(.*\.(gif|png|jpg))$
  static_files: resources/images/\1
  upload: resources/images/.*\.(gif|png|jpg)$
  
  
- url: /(.*\.(webm|mp4))$
  static_files: resources/videos/\1
  upload: resources/videos/.*\.(webm|mp4)$
  
  
- url: /(.*\.(eot|woff|ttf|svg))$
  static_files: resources/fonts/\1
  upload: resources/fonts/.*\.(ot|woff|ttf|svg)$
  
  
- url: /.*
  script: _go_app
  
  